# Generated by Django 5.2 on 2025-04-09 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SassaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255, unique=True)),
                ('id_number', models.CharField(max_length=13)),
                ('phone_number', models.CharField(max_length=20)),
                ('sapo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('risk', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sassa_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SassaStatusCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('outcome_period', models.CharField(blank=True, max_length=10, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_checks', to='sassa_notifier.sassaapplication')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SassaOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('paid', models.BooleanField(blank=True, null=True)),
                ('filed', models.DateTimeField(blank=True, null=True)),
                ('payday', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='sassa_notifier.sassastatuscheck')),
            ],
        ),
    ]
