# Generated by Django 5.2 on 2025-04-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sassa_notifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sassastatuscheck',
            name='checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
